version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
